import { useEffect } from 'react'

// DI SEGUITO CREIAMO UN HOOK PERSONALIZZATO UTILE AL CONTROLLO DEL TITLE DEL DOCUMENT 
// NOTA COME ABBIAMO UTILIZZATO LA KEY useNomeHook PER CREARE UN CUSTOM HOOK, CONVENZIONE UTILIZZATA PER LA STESURA DEL CODICE
const useDocumentTitle = ({ count }) => {

    // AGGIORNIAMO IL TITOLO DEL DOCUMENTO TRAMITE USEEFFECT
	useEffect(() => {
		document.title = `Count: ${count}`
	}, [count])

    // ELIMINIAMO IL RITORNO DI JSX IN QUANTO NON ANDIAMO A CREARNE
    // NEGLI HOOKS PERSONALIZZATI ANDIAMO AD IMPLEMENTARE SOLAMENTE LA LOGICA 
    // return (

    // )
}

export default useDocumentTitle
